config/routes.rb
Rails.application.routes.draw do
  resources :alerts

  devise_for :users, :skip => [:registrations], :controllers => { sessions: 'sessions'}                                        
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
    put 'users/:id' => 'devise/registrations#update', :as => 'user_registration'            
  end

  post 'users', to: 'users#set_reg', defaults: {format: :json}
  get 'bus/password', to: 'clients#get_password', defaults: {format: :json}
  resources 'passwords'
  get 'password', to: 'passwords#show'
  post 'password', to: 'passwords#create'
  resources :clients

  resources :locations 

  resources :routes

  resources :buses
  get 'api/send_gcm' => 'welcome#send_gcm', defaults: {format: :json}

  get 'api/locations/buses', to: 'locations#buses', defaults: {format: :json}
  get 'api/client_panic', to: 'clients#client_panic', defaults: {format: :json}

  get 'welcome/index'

  root 'welcome#index'

end

app/models/alert.rb
class Alert < ActiveRecord::Base
  belongs_to :client
  before_validation :set_client_id
  validates_presence_of :alert_type
  validates_presence_of :latitude
  validates_presence_of :longitude
  validates_presence_of :client_id
  validates_presence_of :email

  enum harrasment_type: [:mirada, :verbal, :tocamiento, :exhibicion]

  def set_client_id
    user = Client.find_by(email: self.email)
    puts user
    if user
      self.client_id = user.id
      self.email = user.email
    end
  end
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  before_action :set_alert, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:show, :edit, :update, :destroy, :index]

  # GET /alerts
  # GET /alerts.json
  def index
    @alerts = Alert.all
  end

  # GET /alerts/1
  # GET /alerts/1.json
  def show
  end

  # GET /alerts/new
  def new
    @alert = Alert.new
  end

  # GET /alerts/1/edit
  def edit
  end

  # POST /alerts
  # POST /alerts.json
  def create
    puts alert_params.class
    @alert = Alert.new(alert_params)
    respond_to do |format|
      if @alert.save
        key = ENV['GCMKEY']
        gcm = GCM.new(key)
        client = @alert.client
        options = { data: {msg: "ALERTA ENVIADA AL ADMINISTRADOR"}, collapse_key: "ALERTA"}
        reg_id = [client.reg_id]
        response = gcm.send(reg_id, options)
        puts response
        format.html { redirect_to @alert, notice: 'Alert was successfully created.' }
        format.json { render json: {msg: "ALERTA ENVIADA AL ADMINISTRADOR",  response: response} }
      else
        format.html { render :new }
        format.json { render json: @alert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alerts/1
  # PATCH/PUT /alerts/1.json
  def update
    respond_to do |format|
      if @alert.update(alert_params)
        format.html { redirect_to @alert, notice: 'Alert was successfully updated.' }
        format.json { render :show, status: :ok, location: @alert }
      else
        format.html { render :edit }
        format.json { render json: @alert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alerts/1
  # DELETE /alerts/1.json
  def destroy
    @alert.destroy
    respond_to do |format|
      format.html { redirect_to alerts_url, notice: 'Alert was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alert
      @alert = Alert.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alert_params
      params.require(:alert).permit(:alert_type, :latitude, :longitude,:email, :harrasment_type)
    end
end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/views/alerts/_form.html.erb
<%= simple_form_for(@alert) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :alert_type %>
    <%= f.input :latitude %>
    <%= f.input :longitude %>
    <%= f.input :email, as: :string %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/alerts/edit.html.erb
<h1>Editing alert</h1>

<%= render 'form' %>

<%= link_to 'Show', @alert %> |
<%= link_to 'Back', alerts_path %>

app/views/alerts/index.html.erb
<h1>Listing alerts</h1>

<div id='map' class='dark'></div>


<table>
  <thead>
    <tr>
      <th>Tipo</th>
      <th>Latitud</th>
      <th>Longitud</th>
      <th>Cliente</th>
      <th>Tipo de acoso</th>
      <th>Hora de alerta</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alerts.each do |alert| %>
      <tr>
        <% if alert.alert_type == 1 %>
          <td>Yo</td>
        <% else %>
          <td>Alguien más</td>
        <% end %>
        <td><%= alert.latitude %></td>
        <td><%= alert.longitude %></td>
        <td><%= alert.email %></td>
        <td><%= alert.harrasment_type %></td>
        <td><%= local_time(alert.created_at) %></td>
        <td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alert', new_alert_path %>

app/views/alerts/new.html.erb
<h1>New alert</h1>

<%= render 'form' %>

<%= link_to 'Back', alerts_path %>

app/views/alerts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @alert.alert_type %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @alert.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @alert.longitude %>
</p>

<p>
  <strong>Client:</strong>
  <%= @alert.client_id %>
</p>

<%= link_to 'Edit', edit_alert_path(@alert) %> |
<%= link_to 'Back', alerts_path %>