config/routes.rb
Rails.application.routes.draw do
  resources :alerts

  devise_for :users, :skip => [:registrations], :controllers => { sessions: 'sessions'}                                        
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
    put 'users/:id' => 'devise/registrations#update', :as => 'user_registration'            
  end

  post 'users', to: 'users#set_reg', defaults: {format: :json}
  get 'bus/password', to: 'clients#get_password', defaults: {format: :json}
  resources 'passwords'
  get 'password', to: 'passwords#show'
  post 'password', to: 'passwords#create'
  resources :clients

  resources :locations 

  resources :routes

  resources :buses
  get 'api/send_gcm' => 'welcome#send_gcm', defaults: {format: :json}

  get 'api/locations/buses', to: 'locations#buses', defaults: {format: :json}
  get 'api/client_panic', to: 'clients#client_panic', defaults: {format: :json}

  get 'welcome/index'

  root 'welcome#index'

end

app/controllers/buses_controller.rb
class BusesController < ApplicationController
  before_action :set_bus, only: [:show, :edit, :update, :destroy]

  # GET /buses
  # GET /buses.json
  def index
    @buses = Bus.all
  end

  # GET /buses/1
  # GET /buses/1.json
  def show
  end

  # GET /buses/new
  def new
    @bus = Bus.new
  end

  # GET /buses/1/edit
  def edit
  end

  # POST /buses
  # POST /buses.json
  def create
    @bus = Bus.new(bus_params)

    respond_to do |format|
      if @bus.save
        format.html { redirect_to @bus, notice: 'Bus was successfully created.' }
        format.json { render :show, status: :created, location: @bus }
      else
        format.html { render :new }
        format.json { render json: @bus.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buses/1
  # PATCH/PUT /buses/1.json
  def update
    respond_to do |format|
      if @bus.update(bus_params)
        format.html { redirect_to @bus, notice: 'Bus was successfully updated.' }
        format.json { render :show, status: :ok, location: @bus }
      else
        format.html { render :edit }
        format.json { render json: @bus.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buses/1
  # DELETE /buses/1.json
  def destroy
    @bus.destroy
    respond_to do |format|
      format.html { redirect_to buses_url, notice: 'Bus was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bus
      @bus = Bus.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bus_params
      params.require(:bus).permit(:placa, :route_id, :name, :reg_id)
    end
end

app/helpers/buses_helper.rb
module BusesHelper
end

app/views/buses/_form.html.erb
<%= simple_form_for(@bus) do |f| %>
  <% if @bus.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bus.errors.count, "error") %> prohibited this bus from being saved:</h2>

      <ul>
      <% @bus.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.input :placa %>
  </div>
  <div class="field">
    <%= f.association :route %>
  </div>
  <div class="field">
    <%= f.input :name %>
  </div>
  <div class="field">
    <%= f.input :reg_id %>
  </div>
  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/buses/edit.html.erb
<h1>Editing bus</h1>

<%= render 'form' %>

<%= link_to 'Show', @bus %> |
<%= link_to 'Back', buses_path %>

app/views/buses/index.html.erb
<h1>Listing buses</h1>

<table>
  <thead>
    <tr>
      <th>Placa</th>
      <th>Ruta</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buses.each do |bus| %>
      <tr>
        <td><%= bus.placa %></td>
        <td><%= bus.route.name %></td>
        <td><%= bus.name %></td>
        <td><%= link_to 'Show', bus %></td>
        <td><%= link_to 'Edit', edit_bus_path(bus) %></td>
        <td><%= link_to 'Destroy', bus, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bus', new_bus_path %>

app/views/buses/new.html.erb
<h1>New bus</h1>

<%= render 'form' %>

<%= link_to 'Back', buses_path %>

app/views/buses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Placa:</strong>
  <%= @bus.placa %>
</p>

<p>
  <strong>Ruta:</strong>
  <%= @bus.route.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @bus.name %>
</p>

<%= link_to 'Edit', edit_bus_path(@bus) %> |
<%= link_to 'Back', buses_path %>